=== wangy319/Robotis_task_scheduling/xml_format_in.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
targetNamespace="http://exjobb18.cs.lth.se"
xmlns="http://exjobb18.cs.lth.se"
elementFormDefault="qualified">

<xs:element name="Assembly">
	<xs:complexType>
		<xs:sequence>

			<xs:element name="Trays">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="Tray" maxOccurs="unbounded">
							<xs:complexType>
								<xs:attribute name="id" use="required"/>
							</xs:complexType>
						</xs:element>
					</xs:sequence>
				</xs:complexType>
			</xs:element>

			<xs:element name="Fixtures">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="Fixture" maxOccurs="unbounded">
							<xs:complexType>
								<xs:attribute name="id" type="xs:string" use="required"/>
							</xs:complexType>
						</xs:element>
					</xs:sequence>
				  </xs:complexType>
			</xs:element>

			<xs:element name="Components">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="Component" maxOccurs="unbounded">
							<xs:complexType>
								<xs:attribute name="id" type="xs:string" use="required"/>
							</xs:complexType>
						</xs:element>
					</xs:sequence>
				</xs:complexType>
			</xs:element>

			<xs:element name="Tools">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="Tool" maxOccurs="unbounded">
							<xs:complexType>
								<xs:attribute name="id" type="xs:string" use="required"/>
							</xs:complexType>
						</xs:element>
					</xs:sequence>
				</xs:complexType>
			</xs:element>

			<xs:element name="Machines">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="Machine" maxOccurs="unbounded">
							<xs:complexType>
								<xs:attribute name="id" type="xs:string" use="required"/>
							</xs:complexType>
						</xs:element>
					</xs:sequence>
				</xs:complexType>
			</xs:element>

			<xs:element name="Tasks">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="Task" maxOccurs="unbounded">
							<xs:complexType>
								<xs:sequence>
									<xs:element name="Tray" minOccurs="0">
										<xs:complexType>
											<xs:attribute name="id" type="xs:string" use="required"/>
										</xs:complexType>
									</xs:element>
									<xs:element name="Fixture" minOccurs="0">
										<xs:complexType>
											<xs:attribute name="id" type="xs:string" use="required"/>
										</xs:complexType>
									</xs:element>
									<xs:element name="ComponentsUsed" minOccurs="0">
										<xs:complexType>
											<xs:sequence>
												<xs:element name="Component" maxOccurs="unbounded">
													<xs:complexType>
														<xs:attribute name="id" type="xs:string" use="required"/>
													</xs:complexType>
												</xs:element>
											</xs:sequence>
										</xs:complexType>
									</xs:element>
									<xs:element name="ComponentCreated" minOccurs="0">
										<xs:complexType>
											<xs:attribute name="id" type="xs:string" use="required"/>
										</xs:complexType>
									</xs:element>
									<xs:element name="ToolNeeded" minOccurs="0">
										<xs:complexType>
											<xs:attribute name="id" type="xs:string" use="required"/>
										</xs:complexType>
									</xs:element>
									<xs:element name="Putting" minOccurs="0">
										<xs:complexType/>
									</xs:element>
									<xs:element name="Mounting" minOccurs="0">
										<xs:complexType/>
									</xs:element>
									<xs:element name="Taking" minOccurs="0">
										<xs:complexType/>
									</xs:element>
									<xs:element name="Moving" minOccurs="0">
										<xs:complexType/>
									</xs:element>
								</xs:sequence>
								<xs:attribute name="id" type="xs:string" use="required"/>
								<xs:attribute name="Duration" type="xs:positiveInteger" use="required"/>
								<xs:attribute name="EndPos" type="xs:string" use="required"/>
								<xs:attribute name="StartPos" type="xs:string" use="required"/>
							</xs:complexType>
						</xs:element>
					</xs:sequence>
				</xs:complexType>
			</xs:element>

			<xs:element name="Ordered">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="Group" maxOccurs="unbounded">
							<xs:complexType>
								<xs:sequence>
									<xs:element name="Task" maxOccurs="unbounded">
										<xs:complexType>
											<xs:attribute name="id" type="xs:string" use="required"/>
										</xs:complexType>
									</xs:element>
								</xs:sequence>
							</xs:complexType>
						</xs:element>
					</xs:sequence>
				</xs:complexType>
			</xs:element>

			<xs:element name="Concurrent">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="Group" maxOccurs="unbounded">
							<xs:complexType>
								<xs:sequence>
									<xs:element name="Task" maxOccurs="unbounded">
										<xs:complexType>
											<xs:attribute name="id" type="xs:string" use="required"/>
										</xs:complexType>
									</xs:element>
								</xs:sequence>
							</xs:complexType>
						</xs:element>
					</xs:sequence>
				</xs:complexType>
			</xs:element>

			<xs:element name="ToolChanges">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="Change" maxOccurs="unbounded">
							<xs:complexType>
								<xs:attribute name="TaskId" type="xs:string" use="required"/>
								<xs:attribute name="ToolId" type="xs:string" use="required"/>
							</xs:complexType>
						</xs:element>
					</xs:sequence>
				</xs:complexType>
			</xs:element>

			<xs:element name="DefaultTools">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="Default" maxOccurs="unbounded">
							<xs:complexType>
								<xs:attribute name="MachineId" type="xs:string" use="required"/>
								<xs:attribute name="ToolId" type="xs:string" use="required"/>
							</xs:complexType>
						</xs:element>
					</xs:sequence>
				</xs:complexType>
			</xs:element>

		</xs:sequence>
	</xs:complexType>
</xs:element>

</xs:schema>

=== wangy319/Robotis_task_scheduling/MiniZinc/Model6/TestFiles/multipleFixtureOperations2.xml
<?xml version="1.0" encoding="UTF-8"?>

<Assembly xmlns="http://exjobb18.cs.lth.se"
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:schemaLocation="http://exjobb18.cs.lth.se http://exjobb18.cs.lth.se/xml_format_in.xsd">

	<Cycles nbr="1"/>

	<Output id="Output"/>

	<Tray id="top-tray"/>
	<Tray id="Button tray"/>
	<Tray id="Ring tray"/>
	<Tray id="Sticker tray"/>

	<Fixture id="Front fixture"/>

	<Component id="Top"/>
	<Component id="Button"/>
	<Component id="Ring"/>
	<Component id="Sticker"/>
	<Component id="Top-Button"/>
	<Component id="Top-Button-Ring"/>
	<Component id="Top-Button-Ring-Sticker"/>

	<Subcomponent id="Top-Button">
		<Component id="Top"/>
		<Component id="Button"/>
	</Subcomponent>
	<Subcomponent id="Top-Button-Ring">
		<Component id="Top-Button"/>
		<Component id="Ring"/>
	</Subcomponent>
	<Subcomponent id="Top-Button-Ring-Sticker">
		<Component id="Top-Button-Ring"/>
		<Component id="Sticker"/>
	</Subcomponent>


	<Tool id="tool1"/>
	<Tool id="tool2"/>

	<Machine id="m1"/>
	<Machine id="m2"/>

	<Task id="Take top" Duration="5">
		<Tray id="top-tray"/>
		<Component id="Top"/>
		<ToolNeeded id="tool1"/>
		<Action id="Taking"/>
	</Task>
	<Task id="Put top in fixture" Duration="10">
		<Fixture id="Front fixture"/>
		<Component id="Top"/>
		<ToolNeeded id="tool1"/>
		<Action id="Putting"/>
	</Task>
	<Task id="Take button" Duration="5">
		<Tray id="Button tray"/>
		<Component id="Button"/>
		<ToolNeeded id="tool1"/>
		<Action id="Taking"/>
	</Task>
	<Task id="Mount button on top" Duration="25">
		<Fixture id="Front fixture"/>
		<Component id="Top"/>
		<Component id="Button"/>
		<ComponentCreated id="Top-Button"/>
		<ToolNeeded id="tool1"/>
		<Action id="Mounting"/>
	</Task>
	<Task id="Take ring" Duration="10">
		<Tray id="Ring tray"/>
		<Component id="Ring"/>
		<ToolNeeded id="tool1"/>
		<Action id="Taking"/>
	</Task>
	<Task id="Mount ring on top-button" Duration="260">
		<Component id="Top-Button"/>
		<Component id="Ring"/>
		<ComponentCreated id="Top-Button-Ring"/>
		<ToolNeeded id="tool1"/>
		<Action id="Mounting"/>
		<Fixture id="Front fixture"/>
	</Task>
	<Task id="Take top-button-ring" Duration="5">
		<Component id="Top-Button-Ring"/>
		<ToolNeeded id="tool1"/>
		<Action id="Taking"/>
		<Fixture id="Front fixture"/>
	</Task>
	<Task id="Do some move with top-button-ring" Duration="5">
		<Component id="Top-Button-Ring"/>
		<ToolNeeded id="tool1"/>
		<Action id="Moving"/>
	</Task>
	<Task id="Put top-button-ring in fixture" Duration="5">
		<Component id="Top-Button-Ring"/>
		<ToolNeeded id="tool1"/>
		<Action id="Putting"/>
		<Fixture id="Front fixture"/>
	</Task>
	<Task id="Take sticker" Duration="10">
		<Tray id="Sticker tray"/>
		<Component id="Sticker"/>
		<ToolNeeded id="tool1"/>
		<Action id="Taking"/>
	</Task>
	<Task id="Mount sticker on top-button-ring" Duration="260">
		<Component id="Sticker"/>
		<Component id="Top-Button-Ring"/>
		<ComponentCreated id="Top-Button-Ring-Sticker"/>
		<ToolNeeded id="tool1"/>
		<Action id="Mounting"/>
		<Fixture id="Front fixture"/>
	</Task>
	<Task id="Take top-button-ring-sticker" Duration="5">
		<Component id="Top-Button-Ring-Sticker"/>
		<ToolNeeded id="tool1"/>
		<Action id="Taking"/>
		<Fixture id="Front fixture"/>
	</Task>
	<Task id="Put top-button-ring-sticker on table" Duration="5">
		<Component id="Top-Button-Ring-Sticker"/>
		<ToolNeeded id="tool1"/>
		<Action id="Putting"/>
		<Output id="Output"/>
	</Task>

	<OrderedGroup>
		<Task id="Take top-button-ring"/>
		<Task id="Do some move with top-button-ring"/>
		<Task id="Put top-button-ring in fixture"/>
	</OrderedGroup>

	<ToolChangeDurations>
		<Change FromToolId="tool1" ToToolId="tool2" Duration="60"/>
		<Change FromToolId="tool2" ToToolId="tool1" Duration="60"/>
	</ToolChangeDurations>

</Assembly>

=== wangy319/Robotis_task_scheduling/MiniZinc/Model2/XML/xml_in_old.xml
<?xml version="1.0" encoding="UTF-8"?>

<Assembly xmlns="http://exjobb18.cs.lth.se"
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:schemaLocation="http://exjobb18.cs.lth.se http://exjobb18.cs.lth.se/xml_format_in.xsd">
	<Trays>
		<Tray id="Top tray"/>
		<Tray id="Button tray"/>
		<Tray id="Ring tray"/>
		<Tray id="Switch tray"/>
	</Trays>

	<Fixtures>
		<Fixture id="Front fixture"/>
	</Fixtures>

	<Components>
		<Component id="Top"/>
		<Component id="Button"/>
		<Component id="Ring"/>
		<Component id="Bottom"/>
		<Component id="Switch"/>
		<Component id="Top-Button"/>
		<Component id="Top-Button-Ring"/>
		<Component id="Bottom-Switch"/>
		<Component id="Complete"/>
	</Components>

	<Tools>
		<Tool id="tool1"/>
		<Tool id="tool2"/>
	</Tools>

	<Machines>
		<Machine id="m1"/>
		<Machine id="m2"/>
	</Machines>

	<Tasks>
		<Task id="Take top" Duration="5" EndPos="4,9" StartPos="4,9">
			<Tray id="Top tray"/>
			<ComponentsUsed>
				<Component id="Top"/>
			</ComponentsUsed>
			<ToolNeeded id="tool1"/>
			<Action>Taking</Action>
		</Task>
		<Task id="Put top in fixture" Duration="10" EndPos="8,2" StartPos="8,2">
			<Fixture id="Front fixture"/>
			<ComponentsUsed>
				<Component id="Top"/>
			</ComponentsUsed>
			<ToolNeeded id="tool1"/>
			<Action>Putting</Action>
		</Task>
		<Task id="Take button" Duration="5" EndPos="5,2" StartPos="5,2">
			<Tray id="Button tray"/>
			<ComponentsUsed>
				<Component id="Button"/>
			</ComponentsUsed>
			<ToolNeeded id="tool1"/>
			<Action>Taking</Action>
		</Task>
		<Task id="Mount button on top" Duration="25" EndPos="8,2" StartPos="8,2">
			<Fixture id="Front fixture"/>
			<ComponentsUsed>
				<Component id="Top"/>
				<Component id="Button"/>
			</ComponentsUsed>
			<ComponentCreated id="Top-Button"/>
			<ToolNeeded id="tool1"/>
			<Action>Mounting</Action>
		</Task>
		<Task id="Take top-button from fixture" Duration="5" EndPos="8,2" StartPos="8,2">
			<Fixture id="Front fixture"/>
			<ComponentsUsed>
				<Component id="Top-Button"/>
			</ComponentsUsed>
			<ToolNeeded id="tool1"/>
			<Action>Taking</Action>
		</Task>
		<Task id="Angle top-bottom" Duration="5" EndPos="8,2" StartPos="8,2">
			<Fixture id="Front fixture"/>
			<ComponentsUsed>
				<Component id="Top-Button"/>
			</ComponentsUsed>
			<ToolNeeded id="tool1"/>
			<Action>Moving</Action>
		</Task>
		<Task id="Lift top-button, hold top-button" Duration="5" EndPos="7,9" StartPos="8,2">
			<ComponentsUsed>
				<Component id="Top-Button"/>
			</ComponentsUsed>
			<ToolNeeded id="tool1"/>
			<Action>Moving</Action>
		</Task>
		<Task id="Lift top-button, support" Duration="5" EndPos="7,9" StartPos="8,2">
			<ComponentsUsed>
				<Component id="Top-Button"/>
			</ComponentsUsed>
			<Action>Moving</Action>
		</Task>
		<Task id="Turn top-button" Duration="20" EndPos="7,9" StartPos="7,9">
			<ComponentsUsed>
				<Component id="Top-Button"/>
			</ComponentsUsed>
			<ToolNeeded id="tool1"/>
			<Action>Moving</Action>
		</Task>
		<Task id="Take ring" Duration="10" EndPos="14,9" StartPos="14,9">
			<Tray id="Ring tray"/>
			<ComponentsUsed>
				<Component id="Ring"/>
			</ComponentsUsed>
			<ToolNeeded id="tool1"/>
			<Action>Taking</Action>
		</Task>
		<Task id="Mount ring on top-button, hold" Duration="260" EndPos="7,9" StartPos="7,9">
			<ComponentsUsed>
				<Component id="Top-Button"/>
				<Component id="Ring"/>
			</ComponentsUsed>
			<ComponentCreated id="Top-Button-Ring"/>
			<ToolNeeded id="tool1"/>
			<Action>Mounting</Action>
		</Task>
		<Task id="Mount ring on top-button, mount" Duration="260" EndPos="7,9" StartPos="7,9">
			<ComponentsUsed>
				<Component id="Top-Button"/>
				<Component id="Ring"/>
			</ComponentsUsed>
			<ComponentCreated id="Top-Button-Ring"/>
			<ToolNeeded id="tool1"/>
			<Action>Mounting</Action>
		</Task>
		<Task id="Fixate top-button-ring" Duration="15" EndPos="9,2" StartPos="9,2">
			<Fixture id="Front fixture"/>
			<ComponentsUsed>
				<Component id="Top-Button-Ring"/>
			</ComponentsUsed>
			<ToolNeeded id="tool1"/>
			<Action>Moving</Action>
		</Task>
		<Task id="Put top-button-ring in top-tray" Duration="5" EndPos="4,9" StartPos="4,9">
			<Tray id="Top tray"/>
			<ComponentsUsed>
				<Component id="Top-Button-Ring"/>
			</ComponentsUsed>
			<ToolNeeded id="tool1"/>
			<Action>Putting</Action>
		</Task>
		<Task id="Change to bottom-grabber tool" Duration="60" EndPos="8,12" StartPos="8,12"/>
		<Task id="Take top-button-ring from top-tray" Duration="5" EndPos="4,9" StartPos="4,9">
			<Tray id="Top tray"/>
			<ComponentsUsed>
				<Component id="Top-Button-Ring"/>
			</ComponentsUsed>
			<ToolNeeded id="tool1"/>
			<Action>Taking</Action>
		</Task>
		<Task id="Take bottom" Duration="5" EndPos="11,9" StartPos="11,9">
			<Tray id="Bottom tray"/>
			<ComponentsUsed>
				<Component id="Bottom"/>
			</ComponentsUsed>
			<ToolNeeded id="tool2"/>
			<Action>Taking</Action>
		</Task>
		<Task id="Put bottom in fixture" Duration="10" EndPos="8,2" StartPos="8,2">
			<Fixture id="Front fixture"/>
			<ComponentsUsed>
				<Component id="Bottom"/>
			</ComponentsUsed>
			<ToolNeeded id="tool2"/>
			<Action>Putting</Action>
		</Task>
		<Task id="Take switch" Duration="5" EndPos="12,5" StartPos="12,5">
			<Tray id="Switch tray"/>
			<ComponentsUsed>
				<Component id="Switch"/>
			</ComponentsUsed>
			<ToolNeeded id="tool2"/>
			<Action>Taking</Action>
		</Task>
		<Task id="Mount switch in bottom" Duration="15" EndPos="8,2" StartPos="8,2">
			<Fixture id="Front fixture"/>
			<ComponentsUsed>
				<Component id="Bottom"/>
				<Component id="Switch"/>
			</ComponentsUsed>
			<ComponentCreated id="Bottom-Switch"/>
			<ToolNeeded id="tool2"/>
			<Action>Mounting</Action>
		</Task>
		<Task id="Take bottom-switch" Duration="0" EndPos="8,2" StartPos="8,2">
			<Fixture id="Front fixture"/>
			<ComponentsUsed>
				<Component id="Bottom-Switch"/>
			</ComponentsUsed>
			<ToolNeeded id="tool2"/>
			<Action>Taking</Action>
		</Task>
		<Task id="Put bottom-switch on table" Duration="5" EndPos="10,2" StartPos="10,2">
			<ComponentsUsed>
				<Component id="Bottom-Switch"/>
			</ComponentsUsed>
			<ToolNeeded id="tool2"/>
			<Action>Putting</Action>
		</Task>
		<Task id="Mount top-bottom on bottom-switch" Duration="15" EndPos="10,2" StartPos="10,2">
			<ComponentsUsed>
				<Component id="Top-Button"/>
				<Component id="Bottom-Switch"/>
			</ComponentsUsed>
			<ComponentCreated id="Complete"/>
			<ToolNeeded id="tool1"/>
			<Action>Mounting</Action>
		</Task>
	</Tasks>

	<Ordered>
		<Group>
			<Task id="Take top-button from fixture"/>
			<Task id="Angle top-button"/>
			<Task id="Lift top-button, hold top-button"/>
			<Task id="Turn top-button"/>
			<Task id="Mount ring on top-button, hold"/>
			<Task id="Fixate top-button"/>
			<Task id="Put top-button in top-tray"/>
		</Group>
	</Ordered>

	<Concurrent>
		<Group>
			<Task id="Lift top-button, hold top-button"/>
			<Task id="Lift top-button, support"/>
		</Group>
		<Group>
			<Task id="Mount ring on top-button, hold"/>
			<Task id="Mount ring on top-button, mount"/>
		</Group>
	</Concurrent>

	<ToolChanges>
		<Change TaskId="Change to bottom-grabber tool" ToolId="tool2"/>
	</ToolChanges>

	<DefaultTools>
		<Default MachineId="m1" ToolId="tool2"/>
		<Default MachineId="m2" ToolId="tool2"/>
	</DefaultTools>
</Assembly>

=== wangy319/Robotis_task_scheduling/MiniZinc/Model2/XML/xml_in_group_lift.xml
<?xml version="1.0" encoding="UTF-8"?>

<Assembly xmlns="http://exjobb18.cs.lth.se"
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:schemaLocation="http://exjobb18.cs.lth.se http://exjobb18.cs.lth.se/xml_format_in.xsd">

	<Tray id="Top tray"/>
	<Tray id="Button tray"/>
	<Tray id="Ring tray"/>
	<Tray id="Bottom tray"/>
	<Tray id="Switch tray"/>

	<Fixture id="Front fixture"/>

	<Component id="Top"/>
	<Component id="Button"/>
	<Component id="Ring"/>
	<Component id="Bottom"/>
	<Component id="Switch"/>
	<Component id="Top-Button"/>
	<Component id="Top-Button-Ring"/>
	<Component id="Bottom-Switch"/>
	<Component id="Complete"/>

	<Tool id="tool1"/>
	<Tool id="tool2"/>

	<Machine id="m1"/>
	<Machine id="m2"/>

	<StartPos pos="7,9"/>

	<Task id="Take top" Duration="5" EndPos="4,9" StartPos="4,9">
		<Tray id="Top tray"/>
		<Component id="Top"/>
		<ToolNeeded id="tool1"/>
		<Action id="Taking"/>
	</Task>
	<Task id="Put top in fixture" Duration="10" EndPos="8,2" StartPos="8,2">
		<Fixture id="Front fixture"/>
		<Component id="Top"/>
		<ToolNeeded id="tool1"/>
		<Action id="Putting"/>
	</Task>
	<Task id="Take button" Duration="5" EndPos="5,2" StartPos="5,2">
		<Tray id="Button tray"/>
		<Component id="Button"/>
		<ToolNeeded id="tool1"/>
		<Action id="Taking"/>
	</Task>
	<Task id="Mount button on top" Duration="25" EndPos="8,2" StartPos="8,2">
		<Fixture id="Front fixture"/>
		<Component id="Top"/>
		<Component id="Button"/>
		<ComponentCreated id="Top-Button"/>
		<ToolNeeded id="tool1"/>
		<Action id="Mounting"/>
	</Task>
	<Task id="Take top-button from fixture" Duration="5" EndPos="8,2" StartPos="8,2">
		<Fixture id="Front fixture"/>
		<Component id="Top-Button"/>
		<ToolNeeded id="tool1"/>
		<Action id="Taking"/>
	</Task>
	<Task id="Lift Top-Button, hold" Duration="30" EndPos="7,9" StartPos="8,2">
		<Component id="Top-Button"/>
		<ToolNeeded id="tool1"/>
		<Action id="Moving"/>
	</Task>
	<Task id="Lift Top-Button, support" Duration="30" EndPos="7,9" StartPos="8,2">
		<Component id="Top-Button"/>
		<Action id="Moving"/>
	</Task>
	<Task id="Take ring" Duration="10" EndPos="14,9" StartPos="14,9">
		<Tray id="Ring tray"/>
		<Component id="Ring"/>
		<ToolNeeded id="tool1"/>
		<Action id="Taking"/>
	</Task>
	<Task id="Mount ring on top-button, hold" Duration="260" EndPos="7,9" StartPos="7,9">
		<Component id="Top-Button"/>
		<ComponentCreated id="Top-Button-Ring"/>
		<ToolNeeded id="tool1"/>
		<Action id="Mounting"/>
	</Task>
	<Task id="Mount ring on top-button, mount" Duration="260" EndPos="7,9" StartPos="7,9">
		<Component id="Ring"/>
		<ComponentCreated id="Top-Button-Ring"/>
		<ToolNeeded id="tool1"/>
		<Action id="Mounting"/>
	</Task>
	<Task id="Fixate top-button-ring" Duration="15" EndPos="9,2" StartPos="9,2">
		<Fixture id="Front fixture"/>
		<Component id="Top-Button-Ring"/>
		<ToolNeeded id="tool1"/>
		<Action id="Moving"/>
	</Task>
	<Task id="Put top-button-ring in top-tray" Duration="5" EndPos="4,9" StartPos="4,9">
		<Tray id="Top tray"/>
		<Component id="Top-Button-Ring"/>
		<ToolNeeded id="tool1"/>
		<Action id="Putting"/>
	</Task>
	<Task id="Change to bottom-grabber tool" Duration="60" EndPos="8,12" StartPos="8,12"/>
	<Task id="Take top-button-ring from top-tray" Duration="5" EndPos="4,9" StartPos="4,9">
		<Tray id="Top tray"/>
		<Component id="Top-Button-Ring"/>
		<ToolNeeded id="tool1"/>
		<Action id="Taking"/>
	</Task>
	<Task id="Take bottom" Duration="5" EndPos="11,9" StartPos="11,9">
		<Tray id="Bottom tray"/>
		<Component id="Bottom"/>
		<ToolNeeded id="tool2"/>
		<Action id="Taking"/>
	</Task>
	<Task id="Put bottom in fixture" Duration="10" EndPos="8,2" StartPos="8,2">
		<Fixture id="Front fixture"/>
		<Component id="Bottom"/>
		<ToolNeeded id="tool2"/>
		<Action id="Putting"/>
	</Task>
	<Task id="Take switch" Duration="5" EndPos="12,5" StartPos="12,5">
		<Tray id="Switch tray"/>
		<Component id="Switch"/>
		<ToolNeeded id="tool2"/>
		<Action id="Taking"/>
	</Task>
	<Task id="Mount switch in bottom" Duration="15" EndPos="8,2" StartPos="8,2">
		<Fixture id="Front fixture"/>
		<Component id="Bottom"/>
		<Component id="Switch"/>
		<ComponentCreated id="Bottom-Switch"/>
		<ToolNeeded id="tool2"/>
		<Action id="Mounting"/>
	</Task>
	<Task id="Take bottom-switch" Duration="0" EndPos="8,2" StartPos="8,2">
		<Fixture id="Front fixture"/>
		<Component id="Bottom-Switch"/>
		<ToolNeeded id="tool2"/>
		<Action id="Taking"/>
	</Task>
	<Task id="Put bottom-switch on table" Duration="5" EndPos="10,2" StartPos="10,2">
		<Component id="Bottom-Switch"/>
		<ToolNeeded id="tool2"/>
		<Action id="Putting"/>
	</Task>
	<Task id="Mount top-button-ring on bottom-switch" Duration="15" EndPos="10,2" StartPos="10,2">
		<Component id="Top-Button-Ring"/>
		<Component id="Bottom-Switch"/>
		<ComponentCreated id="Complete"/>
		<ToolNeeded id="tool1"/>
		<Action id="Mounting"/>
	</Task>

	<OrderedGroup>
		<Task id="Take top-button from fixture"/>
		<Task id="Lift Top-Button, hold"/>
		<Task id="Mount ring on top-button, hold"/>
	</OrderedGroup>

	<ConcurrentGroup>
		<Task id="Lift Top-Button, hold"/>
		<Task id="Lift Top-Button, support"/>
	</ConcurrentGroup>
	<ConcurrentGroup>
		<Task id="Mount ring on top-button, hold"/>
		<Task id="Mount ring on top-button, mount"/>
	</ConcurrentGroup>

	<ToolChange TaskId="Change to bottom-grabber tool" ToolId="tool2"/>

	<DefaultTool MachineId="m1" ToolId="tool1"/>
	<DefaultTool MachineId="m2" ToolId="tool1"/>

</Assembly>
